services:
  api:
    build: ./api
    ports:
      - "3138:3001"
    env_file: .env
    depends_on:
      - db
    networks:
      - app-network

  landing:
    build: ./landing
    ports:
      - "3129:80"
    networks:
      - app-network

  db:
    image: mysql:8.0
    restart: always
    ports:
      - "9165:3306"
    environment:
      MYSQL_HOST: localhost
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: formulario_db
    volumes:
      - ./db/Dump20250801.sql:/docker-entrypoint-initdb.d/init.sql
      - dbdata:/var/lib/mysql
    networks:
      - app-network

volumes:
  dbdata:

networks:
  tot-network:
    driver: bridge
